// <auto-generated />
using System;
using CourseProjectLiteMK5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseProjectLiteMK5.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230430155437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CourseProjectLiteMK5.Areas.Identity.Data.AccessCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("AccessCodes");

                    b.HasData(
                        new
                        {
                            Id = "fcd115a3-0cc0-4eee-ac1e-e0fc45343e00",
                            Code = "q42ag8",
                            IsActive = true
                        },
                        new
                        {
                            Id = "aee5a858-74d9-49e2-a54b-359b23781ec7",
                            Code = "bjc1SZ",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("CourseProjectLiteMK5.Areas.Identity.Data.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("varchar(8192)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = "46d44d6d-7716-4aa6-a190-3c8a8aa43110",
                            Content = "OBS! Detta kommer jag ej göra och jag uppmanar ingen annan att göra det heller!!OBS!\r\n\r\nSatt och funderade lite bara, skulle denna plan fungera?\r\n\r\nMan är 4st. Alla har pistol, svarta kläder, rånaluva, skyddsväst, mobil, nightvison (Stavning?) och handklovar.\r\n\r\nMobilen: Alla har en mobil med öronsnacka. Ljudlös och man har samtal mellan alla 4. Självklart så har man kontantkort och en billig mobil som man kan dumpa efter rånet.\r\n\r\nDetta sker efter mörkrets inbrott, aldeles innan stängning och när det är folk tomt.\r\nMan ställer bilen ca 1km från kiosken. En lägger sig utanför kisoken i en buske så att man har uppsikt fall om det skulle komma någon. Den andre ställer sig så att han siktar mot dörren. En tar kasörskan och den sista kollar på lagret.\r\nMan slänger ner kasörskan på marken så att hon inte syns ifrån fönstren. Sätter på henne/han handklovar både på fötterna och händerna. Sätter på munkavel + ögonbindel med. Knipsar av alla telefon sladdar. Snor hennes/hans mobil. Man tömmer kassan på pengar. Slår sönder videobanden om det finns video/ljud övervakning. Släcker lamporna låser dörren så att det ser ut som att kiosken har stängt. Sedan så springer man allt var man har till bilen. Kör till den andra flyktbilen som står ca 5mil från den första. Den andra bilen står vid en sjö så att man kan dumpa den första bilen i sjön. Kör ca 10 mil och där står en tredje bil. Man eldar upp den andra. Sedan så åker man till en båt. Åker skit långt ut till havs och slänger ner alla kläder m.m i en sopsäck med sten i och dumpar det i havet. Åker tillbacka till flyktbil nr 3 och åker hem. OBS! Alla snackar engelska under rånet så att kasörskan tror att man är från något annat land.\r\n\r\nSkulle detta funka eller tror ni att man skulle åka dit?\r\n\r\nOBS! Detta kommer jag ej göra och jag uppmanar ingen annan att göra det heller!!OBS!",
                            CreationDate = new DateTime(2004, 9, 14, 22, 54, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tror ni att man kommer åka fast?",
                            UserId = "41c2f21b-c8c0-4e7d-ad69-680ae24d6e37"
                        });
                });

            modelBuilder.Entity("CourseProjectLiteMK5.Areas.Identity.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6cc7e8ce-0da8-40e4-ae7d-e4d49fe44ffc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bbe93e22-5723-4e6b-99d3-51cf31f7437f",
                            CreationDate = new DateTime(2023, 4, 30, 17, 54, 36, 953, DateTimeKind.Local).AddTicks(4301),
                            Email = "admin@administrator.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEDeMzYRGWt6yosW6yP6jOdGJMT2CEUmzyr6YH41cj1zfPY6+J2mHwaINzs9MjVw4cw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "34994a99-83a6-4123-ab70-ceba3c43bb0f",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "41c2f21b-c8c0-4e7d-ad69-680ae24d6e37",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c90d772-7d86-472d-8689-3bad0267d801",
                            CreationDate = new DateTime(2004, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nibbler@nibblerflashback.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJahMAS9wxRd1QbA3+32n+lqLL04N6lOYOhzomu+GU8bsXCoZ5evTnFmfTNXol/X3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cb0f6207-d804-441b-9617-6c277ce95795",
                            TwoFactorEnabled = false,
                            UserName = "Nibbler"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CourseProjectLiteMK5.Areas.Identity.Data.Post", b =>
                {
                    b.HasOne("CourseProjectLiteMK5.Areas.Identity.Data.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CourseProjectLiteMK5.Areas.Identity.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CourseProjectLiteMK5.Areas.Identity.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseProjectLiteMK5.Areas.Identity.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CourseProjectLiteMK5.Areas.Identity.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseProjectLiteMK5.Areas.Identity.Data.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
